name: Build and Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Build app
      run: |
        cd app && sh build.sh
        
    - name: Verify archs of binaries
      run: |
        echo "displaying archs for files:"
        echo "----------------------------------------------------"
        echo "macpaper"
        lipo -archs build/macpaper.app/Contents/MacOS/macpaper
        echo "----------------------------------------------------"
        echo "macpaper-bin"
        lipo -archs build/macpaper.app/Contents/MacOS/macpaper-bin
        echo "----------------------------------------------------"
        echo "glasswp"
        lipo -archs "build/macpaper.app/Contents/MacOS/macpaper Wallpaper Service (glasswp)"
        echo "----------------------------------------------------"
        
    - name: Create DMG
      run: |
        cdmg build/macpaper.app build; mv build/macpaper*.dmg build/macpaper.dmg
